USER-SUPPLIED VALUES:
operator:
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      enabled: true
      name: metrics
      port: 8080
  scanJobsConcurrentLimit: 2
  serviceAccount:
    create: true
trivy:
  ignoreUnfixed: true
  image:
    tag: 0.50.0
  nodeCollector:
    enabled: true
  severity: CRITICAL,HIGH
